In [3]:
import pandas as pd
df=pd.read_csv("StudentsPerformance.csv")
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [7]:
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [8]:
df.tail()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

In [10]:
df.describe()

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

In [11]:
df.isna().sum #check missing values in dataset,TRUE-MISSING VALUE,FALSE-VALUE PRESENT
#SUM-COUNTS THE TRUE VAUES IN EACH COLUMN

<bound method DataFrame.sum of      gender  race/ethnicity  parental level of education  lunch  \
0     False           False                        False  False
1     False           False                        False  False
2     False           False                        False  False
3     False           False                        False  False
4     False           False                        False  False
..      ...             ...                          ...    ...
995   False           False                        False  False
996   False           False                        False  False
997   False           False                        False  False
998   False           False                        False  False
999   False           False                        False  False

     test preparation course  math score  reading score  writing score
0                      False       False          False          False
1                      False       False          False          False
2                      False       False          False          False
3                      False       False          False          False
4                      False       False          False          False
..                       ...         ...            ...            ...
995                    False       False          False          False
996                    False       False          False          False
997                    False       False          False          False
998                    False       False          False          False
999                    False       False          False          False

[1000 rows x 8 columns]>

In [12]:
df.notna() #checks non missing values/notnull()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...
995,True,True,True,True,True,True,True,True
996,True,True,True,True,True,True,True,True
997,True,True,True,True,True,True,True,True
998,True,True,True,True,True,True,True,True
999,True,True,True,True,True,True,True,True

In [4]:
#df.reindex(new_index)
new_index=[10,5,0,2]
df.reindex(new_index)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
10,male,group C,associate's degree,standard,none,58,54,52
5,female,group B,associate's degree,standard,none,71,83,78
0,female,group B,bachelor's degree,standard,none,72,72,74
2,female,group B,master's degree,standard,none,90,95,93

In [5]:
new_index=[10,5,0,2,1001]
df.reindex(new_index) #row 1001 does not exist so it create it with NAN VALUES

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
10,male,group C,associate's degree,standard,none,58.0,54.0,52.0
5,female,group B,associate's degree,standard,none,71.0,83.0,78.0
0,female,group B,bachelor's degree,standard,none,72.0,72.0,74.0
2,female,group B,master's degree,standard,none,90.0,95.0,93.0
1001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
df.reindex(columns=[
    "gender",
    "lunch",
    "math score",
    "reading score",
    "writing score"
])
#this will show only these columns

     gender         lunch  math score  reading score  writing score
0    female      standard          72             72             74
1    female      standard          69             90             88
2    female      standard          90             95             93
3      male  free/reduced          47             57             44
4      male      standard          76             78             75
..      ...           ...         ...            ...            ...
995  female      standard          88             99             95
996    male  free/reduced          62             55             55
997  female  free/reduced          59             71             65
998  female      standard          68             78             77
999  female  free/reduced          77             86             86

[1000 rows x 5 columns]

In [8]:
df.reindex(columns=list(df.columns)+["total_score"])

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,total_score
0,female,group B,bachelor's degree,standard,none,72,72,74,NaN
1,female,group C,some college,standard,completed,69,90,88,NaN
2,female,group B,master's degree,standard,none,90,95,93,NaN
3,male,group A,associate's degree,free/reduced,none,47,57,44,NaN
4,male,group C,some college,standard,none,76,78,75,NaN
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,NaN
996,male,group C,high school,free/reduced,none,62,55,55,NaN
997,female,group C,high school,free/reduced,completed,59,71,65,NaN
998,female,group D,some college,standard,completed,68,78,77,NaN
999,female,group D,some college,free/reduced,none,77,86,86,NaN

In [9]:
new_index=range(0,1010)
df.reindex(new_index,fill_value=10)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
1005,10,10,10,10,10,10,10,10
1006,10,10,10,10,10,10,10,10
1007,10,10,10,10,10,10,10,10
1008,10,10,10,10,10,10,10,10
1009,10,10,10,10,10,10,10,10

In [11]:
df.columns #view all cols

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='object')

In [12]:
#count values
df["gender"].value_counts()

gender
female    518
male      482
Name: count, dtype: int64

In [14]:
df["race/ethnicity"].value_counts

<bound method IndexOpsMixin.value_counts of 0      group B
1      group C
2      group B
3      group A
4      group C
        ...
995    group E
996    group C
997    group C
998    group D
999    group D
Name: race/ethnicity, Length: 1000, dtype: object>

In [15]:
df["race/ethnicity"].unique() #unique values

array(['group B', 'group C', 'group A', 'group D', 'group E'],
      dtype=object)

In [17]:
#check membership
df["gender"].isin(["female"])

0       True
1       True
2       True
3      False
4      False
       ...
995     True
996    False
997     True
998     True
999     True
Name: gender, Length: 1000, dtype: bool

In [21]:
#select rows using labels
#syntax df.loc[row_label,column_label]
df.loc[9:15]  #included end index

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
9,female,group B,high school,free/reduced,none,38,60,50
10,male,group C,associate's degree,standard,none,58,54,52
11,male,group D,associate's degree,standard,none,40,52,43
12,female,group B,high school,standard,none,65,81,73
13,male,group A,some college,standard,completed,78,72,70
14,female,group A,master's degree,standard,none,50,53,58
15,female,group C,some high school,standard,none,69,75,78

In [24]:
#loc with condition
df.loc[df["math score"]<70]

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
1,female,group C,some college,standard,completed,69,90,88
3,male,group A,associate's degree,free/reduced,none,47,57,44
7,male,group B,some college,free/reduced,none,40,43,39
8,male,group D,high school,free/reduced,completed,64,64,67
9,female,group B,high school,free/reduced,none,38,60,50
...,...,...,...,...,...,...,...,...
993,female,group D,bachelor's degree,free/reduced,none,62,72,74
994,male,group A,high school,standard,none,63,63,62
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77

In [25]:
df.loc[1:5,"gender"]

1    female
2    female
3      male
4      male
5    female
Name: gender, dtype: object

In [26]:
#iloc-INTEGER BASED POSITION,SELECTS DATA USING INTEGER POSITIONS(INDEX NUMBERS)
#syntax df.loc[row_POSITION,column_POSITION]
df.iloc[1]

gender                               female
race/ethnicity                      group C
parental level of education    some college
lunch                              standard
test preparation course           completed
math score                               69
reading score                            90
writing score                            88
Name: 1, dtype: object

In [29]:
df.iloc[7:10,0] #end index is NOT INCLUDED IN iloc

7      male
8      male
9    female
Name: gender, dtype: object

# df.index=[100,101,102...]
df.loc[9:15] ##ERRROR
df.iloc[9:15] ##RIGHT

In [37]:
#selectimg columns
df.iloc[0:6][["math score","gender","lunch"]]

   math score  gender         lunch
0          72  female      standard
1          69  female      standard
2          90  female      standard
3          47    male  free/reduced
4          76    male      standard
5          71  female      standard

In [38]:
df.sort_values("math score")

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
59,female,group C,some high school,free/reduced,none,0,17,10
980,female,group B,high school,free/reduced,none,8,24,23
17,female,group B,some high school,free/reduced,none,18,32,28
787,female,group B,some college,standard,none,19,38,32
145,female,group C,some college,free/reduced,none,22,39,33
...,...,...,...,...,...,...,...,...
625,male,group D,some college,standard,completed,100,97,99
623,male,group A,some college,standard,completed,100,96,86
451,female,group E,some college,standard,none,100,92,97
962,female,group E,associate's degree,standard,none,100,100,100
149,male,group E,associate's degree,free/reduced,completed,100,100,93

In [39]:
df.sort_values("math score",ascending=False)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
962,female,group E,associate's degree,standard,none,100,100,100
625,male,group D,some college,standard,completed,100,97,99
458,female,group E,bachelor's degree,standard,none,100,100,100
623,male,group A,some college,standard,completed,100,96,86
451,female,group E,some college,standard,none,100,92,97
...,...,...,...,...,...,...,...,...
145,female,group C,some college,free/reduced,none,22,39,33
787,female,group B,some college,standard,none,19,38,32
17,female,group B,some high school,free/reduced,none,18,32,28
980,female,group B,high school,free/reduced,none,8,24,23
59,female,group C,some high school,free/reduced,none,0,17,10

In [40]:
df.sort_index()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [41]:
df["reading score"].max()

100

In [42]:
df["math score"].min()

0

In [43]:
df["math score"].mean()

np.float64(66.089)

In [44]:
df["math score"].sum()

np.int64(66089)

In [45]:
df["math score"].cumsum() #cumulative sum it keps adding the values one by one and shhws the running totaldf["math score"].min()

0         72
1        141
2        231
3        278
4        354
       ...
995    65823
996    65885
997    65944
998    66012
999    66089
Name: math score, Length: 1000, dtype: int64

In [46]:
df["math score"].idxmax() #returns the row number(index) where the max value occurs

149

In [47]:
df.loc[df["math score"].idxmax()]
#math score max is 100
#index 149 by idxmax
#*****loc retrives the entire row with index 149*****

gender                                       male
race/ethnicity                            group E
parental level of education    associate's degree
lunch                                free/reduced
test preparation course                 completed
math score                                    100
reading score                                 100
writing score                                  93
Name: 149, dtype: object

In [48]:
df["math score"].idxmin()

59

In [50]:
df["math score"].rank() #ASSIGN A RANK TO EACH VALUE,THE SMALLEST VALUE GETS RANK 1,LARGEST VALUE GETS THE HIGHEST RANK
#WHEN THERE IS A TIE PANDAS GIVES THE AVERAGE RAMK

0      644.5
1      575.5
2      946.5
3      102.0
4      737.0
       ...
995    929.0
996    384.0
997    307.5
998    546.5
999    759.5
Name: math score, Length: 1000, dtype: float64

In [51]:
#CORRELATION BETWEEN SCORES
df[["math score","reading score","writing score"]].corr()

               math score  reading score  writing score
math score       1.000000       0.817580       0.802642
reading score    0.817580       1.000000       0.954598
writing score    0.802642       0.954598       1.000000

In [52]:
df[["math score","reading score","writing score"]].cov()

               math score  reading score  writing score
math score     229.918998     180.998958     184.939133
reading score  180.998958     213.165605     211.786661
writing score  184.939133     211.786661     230.907992

In [53]:
df["total score"] = df["math score"] + df["reading score"] + df["writing score"]
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,total score
0,female,group B,bachelor's degree,standard,none,72,72,74,218
1,female,group C,some college,standard,completed,69,90,88,247
2,female,group B,master's degree,standard,none,90,95,93,278
3,male,group A,associate's degree,free/reduced,none,47,57,44,148
4,male,group C,some college,standard,none,76,78,75,229